# Generated by Django 5.0.14 on 2025-12-03 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name (e.g., Dashboard, Delivery)', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Unique code (e.g., dashboard, delivery_management)', max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or name (e.g., fa-dashboard, IconHome)', max_length=50)),
                ('url', models.CharField(help_text='Frontend route (e.g., /dashboard, /delivery)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower number appears first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu for nested items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accesscontrol.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu assignment is active')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who assigned this menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(help_text='Menu item to assign', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accesscontrol.menuitem')),
                ('user', models.ForeignKey(help_text='User to assign menu', on_delete=django.db.models.deletion.CASCADE, related_name='menu_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Menu',
                'verbose_name_plural': 'User Menus',
                'db_table': 'user_menus',
                'ordering': ['menu__order'],
                'unique_together': {('user', 'menu')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='users',
            field=models.ManyToManyField(help_text='Users who have access to this menu', related_name='assigned_menus', through='accesscontrol.UserMenu', to=settings.AUTH_USER_MODEL),
        ),
    ]
