# Generated by Django 5.2.13 on 2026-04-28 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="users",
            field=models.ManyToManyField(
                help_text="Users who have access to this menu",
                related_name="assigned_menus",
                through="accesscontrol.UserMenu",
                through_fields=("menu", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
