# Generated by Django 5.0.14 on 2025-12-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(blank=True, help_text='Username/identifier of person who created invoice', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(default='', help_text='Item/product name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
