# Generated by Django 5.0.14 on 2025-12-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoiceitem_batch_no_invoiceitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
