# Generated by Django 5.0.14 on 2025-12-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='packing',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
