# Generated by Django 5.0.14 on 2025-12-22 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_invoiceitem_company_name_invoiceitem_packing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_status',
            field=models.CharField(choices=[('BILLED', 'Billed'), ('RETURNED', 'Returned'), ('RE_INVOICED', 'Re-invoiced')], default='BILLED', help_text='Billing status of the invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='return_reason',
            field=models.TextField(blank=True, help_text='Reason for returning invoice to billing', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when invoice was returned', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='returned_by',
            field=models.ForeignKey(blank=True, help_text='User who returned the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
