# Generated by Django 5.0.14 on 2025-12-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_invoice_billing_status_invoice_return_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingsession',
            name='packing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PACKED', 'Packed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickingsession',
            name='picking_status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('PICKED', 'Picked'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=20),
        ),
    ]
