# Generated by Django 5.0.14 on 2025-12-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('INVOICED', 'Invoiced'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
