# Generated by Django 5.0.14 on 2025-12-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('INVOICED', 'Invoiced'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='INVOICED', max_length=20),
        ),
        migrations.AlterField(
            model_name='packingsession',
            name='packing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PACKED', 'Packed'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickingsession',
            name='picking_status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('PICKED', 'Picked'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PREPARING', max_length=20),
        ),
    ]
