# Generated by Django 5.0.14 on 2025-12-22 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_invoice_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_status',
            field=models.CharField(choices=[('BILLED', 'Billed'), ('REVIEW', 'Under Review'), ('RE_INVOICED', 'Re-invoiced')], default='BILLED', help_text='Billing status of the invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='return_reason',
            field=models.TextField(blank=True, help_text='Reason for sending invoice to review', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when invoice was sent for review', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='returned_by',
            field=models.ForeignKey(blank=True, help_text='User who sent the invoice for review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('INVOICED', 'Invoiced'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('REVIEW', 'Under Review')], default='INVOICED', max_length=20),
        ),
        migrations.AlterField(
            model_name='packingsession',
            name='packing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PACKED', 'Packed'), ('CANCELLED', 'Cancelled'), ('REVIEW', 'Under Review')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickingsession',
            name='picking_status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('PICKED', 'Picked'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled'), ('REVIEW', 'Under Review')], default='PREPARING', max_length=20),
        ),
    ]
