# Generated by Django 5.0.14 on 2025-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_invoice_billing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingsession',
            name='selected_items',
            field=models.JSONField(blank=True, default=list, help_text='List of item IDs that have been selected/packed so far'),
        ),
        migrations.AddField(
            model_name='pickingsession',
            name='selected_items',
            field=models.JSONField(blank=True, default=list, help_text='List of item IDs that have been selected/picked so far'),
        ),
        migrations.AlterField(
            model_name='deliverysession',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20, verbose_name=('REVIEW', 'Under Review')),
        ),
    ]
