# Generated by Custom edit on 2025-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_packingsession_selected_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10, help_text='Priority of the invoice (LOW, MEDIUM, HIGH)'),
        ),
    ]
