# Generated by custom edit on 2025-12-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_add_invoice_priority'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE sales_packingsession SET selected_items = '[]' WHERE selected_items IS NULL;
            UPDATE sales_pickingsession SET selected_items = '[]' WHERE selected_items IS NULL;
            """,
            reverse_sql="""
            -- no-op reverse
            """,
        ),
    ]
