# Generated by Django 5.0.14 on 2025-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_fix_selected_items_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysession',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
