# Generated by Django 5.0.14 on 2025-12-22 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_deliverysession_delivery_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='returned_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='returned_by',
        ),
        migrations.CreateModel(
            name='InvoiceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.TextField(help_text='Reason for sending invoice to review')),
                ('returned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when invoice was sent for review')),
                ('returned_from_section', models.CharField(choices=[('PICKING', 'Picking Section'), ('PACKING', 'Packing Section'), ('DELIVERY', 'Delivery Section')], help_text='Section from which the invoice was returned for review', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the issue was resolved', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the invoice was corrected and re-invoiced', null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_return', to='sales.invoice')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_invoices', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(help_text='User who sent the invoice for review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
    ]
