# Generated by Django 5.0.14 on 2025-12-24 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_remove_deliverysession_delivered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysession',
            name='delivered_by',
            field=models.ForeignKey(blank=True, help_text='Person who completed the delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverysession',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Person who dispatched/started delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
