# Generated by Django 5.0.14 on 2025-12-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_deliverysession_delivered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysession',
            name='delivery_type',
            field=models.CharField(choices=[('COUNTER PICKUP', 'Counter Pickup'), ('COURIER DELIVERY', 'Courier Delivery'), ('COMPANY DELIVERY', 'Company Delivery')], default='COUNTER PICKUP', max_length=20),
        ),
    ]
