# Generated by Django 5.0.14 on 2025-12-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_deliverysession_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysession',
            name='delivery_type',
            field=models.CharField(choices=[('DIRECT', 'Direct Delivery'), ('COURIER', 'Courier Service'), ('INTERNAL', 'Internal Staff')], default='DIRECT', max_length=20),
        ),
    ]
