# Generated by Django 5.0.14 on 2026-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_deliverysession_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysession',
            name='counter_sub_mode',
            field=models.CharField(blank=True, choices=[('patient', 'Direct Patient'), ('company', 'Direct Company')], help_text='Sub-mode for counter pickup: patient or company', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='pickup_company_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='pickup_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='pickup_person_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='pickup_person_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='pickup_person_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
