# Generated by Django 5.0.14 on 2026-01-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_deliverysession_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Item barcode', max_length=100, null=True),
        ),
    ]
