# Generated by Django 5.0.14 on 2026-01-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_deliverysession_counter_sub_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysession',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TO_CONSIDER', 'To Consider'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
