# Generated by Django 5.0.14 on 2026-01-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_invoiceitem_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicereturn',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_returns', to='sales.invoice'),
        ),
    ]
