# Generated by Django 5.0.14 on 2026-01-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_deliverysession_delivery_status'),
        ('sales', '0024_change_invoice_return_to_foreign_key'),
    ]

    operations = [
    ]
