# Generated by Django 5.0.14 on 2026-01-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_merge_20260112_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysession',
            name='courier_slip',
            field=models.FileField(blank=True, null=True, upload_to='courier_slips/'),
        ),
    ]
