# Generated by Django 5.0.14 on 2026-01-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_deliverysession_courier_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysession',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude where delivery was completed', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='delivery_location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='delivery_location_address',
            field=models.TextField(blank=True, help_text='Reverse geocoded address of delivery location', null=True),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude where delivery was completed', max_digits=11, null=True),
        ),
    ]
