# Generated by Django 5.0.14 on 2026-01-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_deliverysession_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered total amount', max_digits=10, null=True),
        ),
    ]
