# Generated by Django 5.0.14 on 2026-01-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0028_invoice_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverysession",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("TO_CONSIDER", "To Consider"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
