# Generated by Django 5.0.14 on 2026-01-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0029_alter_deliverysession_delivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Manually entered total amount",
                max_digits=10,
            ),
        ),
    ]
