# Generated by Django 5.0.14 on 2026-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0030_alter_invoice_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
