# Generated by Django 5.0.14 on 2026-01-24 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0031_alter_invoice_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["-created_at"], name="sales_invoi_created_685357_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="sales_invoi_status_4e3758_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["billing_status"], name="sales_invoi_billing_5e775f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_date"], name="sales_invoi_invoice_b7f3e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "-created_at"], name="sales_invoi_status_2c31ad_idx"
            ),
        ),
    ]
