# Generated by Django 5.0.14 on 2026-01-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_delivery_role"),
        ("sales", "0032_invoice_sales_invoi_created_685357_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysession",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                help_text="Courier service assigned for delivery",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="accounts.courier",
            ),
        ),
    ]
