# Generated by Django 5.0.14 on 2026-01-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0033_deliverysession_courier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="total",
        ),
    ]
