# Generated by Django 5.0.14 on 2026-01-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0034_remove_invoice_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
