# Generated by Django 5.0.14 on 2026-01-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0035_invoice_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="total",
            new_name="Total",
        ),
    ]
