# Generated by Django 5.0.14 on 2026-01-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0036_rename_total_invoice_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="temp_name",
            field=models.CharField(
                blank=True,
                help_text="Temporary name to show when customer address is not available",
                max_length=255,
                null=True,
            ),
        ),
    ]
