# Generated by Django 5.0.14 on 2026-02-10 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0037_add_temp_name_to_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("INVOICED", "Invoiced"),
                    ("PICKING", "Picking"),
                    ("PICKED", "Picked"),
                    ("CHECKING", "Checking"),
                    ("CHECKING_DONE", "Checking Done"),
                    ("PACKING", "Packing"),
                    ("PACKED", "Packed"),
                    ("DISPATCHED", "Dispatched"),
                    ("DELIVERED", "Delivered"),
                    ("REVIEW", "Under Review"),
                ],
                default="INVOICED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PackingBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "box_id",
                    models.CharField(
                        help_text="Unique box identifier (e.g., BOX-INV001-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "box_number",
                    models.IntegerField(
                        help_text="Sequential box number for this invoice (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "is_sealed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the box has been sealed and completed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_boxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_boxes",
                        to="sales.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["invoice", "box_number"],
            },
        ),
        migrations.CreateModel(
            name="BoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of this item in this box",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_assignments",
                        to="sales.invoiceitem",
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_items",
                        to="sales.packingbox",
                    ),
                ),
            ],
            options={
                "ordering": ["box", "item"],
            },
        ),
        migrations.AddIndex(
            model_name="packingbox",
            index=models.Index(
                fields=["invoice", "box_number"], name="sales_packi_invoice_5d464e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packingbox",
            index=models.Index(fields=["box_id"], name="sales_packi_box_id_e40f30_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="packingbox",
            unique_together={("invoice", "box_number")},
        ),
        migrations.AlterUniqueTogether(
            name="boxitem",
            unique_together={("box", "item")},
        ),
    ]
