# Generated by Django 5.0.14 on 2026-02-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0038_add_box_based_packing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="packingbox",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="packingbox",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="packingbox",
            name="invoice",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("INVOICED", "Invoiced"),
                    ("PICKING", "Picking"),
                    ("PICKED", "Picked"),
                    ("PACKING", "Packing"),
                    ("PACKED", "Packed"),
                    ("DISPATCHED", "Dispatched"),
                    ("DELIVERED", "Delivered"),
                    ("REVIEW", "Under Review"),
                ],
                default="INVOICED",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="BoxItem",
        ),
        migrations.DeleteModel(
            name="PackingBox",
        ),
    ]
