# Generated by Django 5.0.14 on 2026-02-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0039_alter_packingbox_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packingsession",
            name="checking_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User currently checking/verifying this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checking_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="packingsession",
            name="checking_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When checking completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="packingsession",
            name="checking_start_time",
            field=models.DateTimeField(
                blank=True, help_text="When checking started", null=True
            ),
        ),
        migrations.AddField(
            model_name="packingsession",
            name="has_same_address_bills",
            field=models.BooleanField(
                default=False,
                help_text="Whether user indicated there are other bills with same address",
            ),
        ),
        migrations.AlterField(
            model_name="packingsession",
            name="packer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packing_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="packingsession",
            name="packing_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CHECKING", "Checking"),
                    ("CHECKING_DONE", "Checking Done"),
                    ("PACKING", "Packing"),
                    ("PACKED", "Packed"),
                    ("CANCELLED", "Cancelled"),
                    ("REVIEW", "Under Review"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "box_id",
                    models.CharField(
                        help_text="Unique box identifier (e.g., BOX-1234-001)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sealed_at",
                    models.DateTimeField(
                        blank=True, help_text="When box was sealed/completed", null=True
                    ),
                ),
                (
                    "is_sealed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether box is sealed and non-editable",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_boxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="sales.invoice",
                    ),
                ),
                (
                    "packing_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="sales.packingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity of this item in this box",
                        max_digits=10,
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.box",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_assignments",
                        to="sales.invoiceitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="box",
            index=models.Index(fields=["box_id"], name="sales_box_box_id_1cec82_idx"),
        ),
        migrations.AddIndex(
            model_name="box",
            index=models.Index(fields=["invoice"], name="sales_box_invoice_6628dc_idx"),
        ),
        migrations.AddIndex(
            model_name="boxitem",
            index=models.Index(fields=["box"], name="sales_boxit_box_id_90073b_idx"),
        ),
        migrations.AddIndex(
            model_name="boxitem",
            index=models.Index(
                fields=["invoice_item"], name="sales_boxit_invoice_84c06c_idx"
            ),
        ),
    ]
