# Generated by Django 5.0.14 on 2026-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0040_packingsession_checking_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingsession",
            name="consolidation_customer_name",
            field=models.CharField(
                blank=True,
                help_text="Customer name used for grouping held bills",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="packingsession",
            name="held_for_consolidation",
            field=models.BooleanField(
                default=False,
                help_text="Whether this bill is held waiting for more bills from same customer",
            ),
        ),
    ]
