# Generated by Django 5.0.14 on 2026-02-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0041_packingsession_consolidation_customer_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packingsession",
            name="held_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who first held the bill for consolidation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
