# Generated by Django 5.0.14 on 2026-02-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0042_packingsession_held_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_hold",
            field=models.BooleanField(
                default=True,
                help_text="Marks invoice as a hold invoice at the time of creation",
            ),
        ),
    ]
