# Generated by Django 5.0.14 on 2026-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0043_invoice_is_hold"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
