# Generated by Django 5.0.14 on 2026-03-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0045_bulkstatusupdatelog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bulkstatusupdatelog",
            new_name="sales_bulks_execute_77f609_idx",
            old_name="sales_bulks_execute_idx",
        ),
    ]
