# Generated by Django 5.0.14 on 2026-03-10 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_tray_status"),
        ("sales", "0046_rename_sales_bulks_execute_idx_sales_bulks_execute_77f609_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("INVOICED", "Invoiced"),
                    ("PICKING", "Picking"),
                    ("PICKED", "Picked"),
                    ("PACKING", "Packing"),
                    ("BOXING", "Boxing"),
                    ("PACKED", "Packed"),
                    ("DISPATCHED", "Dispatched"),
                    ("DELIVERED", "Delivered"),
                    ("REVIEW", "Under Review"),
                ],
                default="INVOICED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PackingTray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("is_sealed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_packing_trays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_trays",
                        to="sales.invoice",
                    ),
                ),
                (
                    "packing_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_trays",
                        to="sales.packingsession",
                    ),
                ),
                (
                    "tray",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packing_assignments",
                        to="accounts.tray",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackingTrayItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tray_assignments",
                        to="sales.invoiceitem",
                    ),
                ),
                (
                    "tray",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.packingtray",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="packingtray",
            index=models.Index(
                fields=["invoice"], name="sales_packi_invoice_61c904_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packingtray",
            unique_together={("invoice", "tray")},
        ),
    ]
