# Generated by Django 5.0.14 on 2026-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0047_add_boxing_status_and_packing_tray_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="self_boxing",
            field=models.BooleanField(
                default=False,
                help_text="True when the packer chose to print address labels themselves (bypasses Boxing Queue)",
            ),
        ),
    ]
