# Generated by Django 5.0.14 on 2026-03-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_tray_status"),
        ("sales", "0049_customer_address3"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingsession",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                help_text="Courier service selected during label printing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packing_sessions",
                to="accounts.courier",
            ),
        ),
        migrations.AddField(
            model_name="packingsession",
            name="label_count",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of address labels printed during boxing"
            ),
        ),
    ]
