# Generated by Django 5.0.14 on 2026-03-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0050_add_label_count_courier_to_packingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingsession",
            name="boxing_group_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Group ID for bills boxed together in multi-boxing",
                max_length=100,
                null=True,
            ),
        ),
    ]
