# Generated by Django 5.0.14 on 2026-03-25 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_tray_status"),
        ("sales", "0051_packingsession_boxing_group_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deliverysession",
            index=models.Index(
                fields=["delivery_status"], name="sales_deliv_deliver_96e377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverysession",
            index=models.Index(
                fields=["invoice", "delivery_status"],
                name="sales_deliv_invoice_81be0f_idx",
            ),
        ),
    ]
