# Generated by Django 5.0.14 on 2026-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0052_deliverysession_sales_deliv_deliver_96e377_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysession",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="delivery_attachments/"
            ),
        ),
    ]
