# Generated by Django 5.0.14 on 2026-04-07 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_courier_service_pricing_fields"),
        ("sales", "0053_deliverysession_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCourierAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Username/name of person who changed the courier",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "old_courier_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of old courier (snapshot)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "new_courier_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of new courier (snapshot)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for change (optional)", null=True
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the courier change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courier_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_audit_logs",
                        to="sales.deliverysession",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Reference to the invoice being delivered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_change_logs",
                        to="sales.invoice",
                    ),
                ),
                (
                    "new_courier",
                    models.ForeignKey(
                        blank=True,
                        help_text="New courier service",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_deliveries",
                        to="accounts.courier",
                    ),
                ),
                (
                    "old_courier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous courier service",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_deliveries",
                        to="accounts.courier",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "-changed_at"],
                        name="sales_deliv_invoice_84253a_idx",
                    ),
                    models.Index(
                        fields=["delivery_session", "-changed_at"],
                        name="sales_deliv_deliver_31a67d_idx",
                    ),
                    models.Index(
                        fields=["-changed_at"], name="sales_deliv_changed_aeb843_idx"
                    ),
                ],
            },
        ),
    ]
