# Generated by Django 5.0.14 on 2026-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0054_deliverycourierauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysession",
            name="box_weights",
            field=models.JSONField(
                blank=True,
                help_text="Array of weights for each box in the delivery",
                null=True,
            ),
        ),
    ]
