# Generated by Django 5.0.14 on 2026-04-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0055_add_box_weights_to_delivery_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone1",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone2",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="deliverysession",
            name="pickup_person_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="salesman",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
