# Generated by Django 5.0.14 on 2026-04-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0058_invoice_is_express_delivery"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deliverysession",
            new_name="sales_deliv_deliver_012620_idx",
            old_name="sales_deliv_delivery_type_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverysession",
            new_name="sales_deliv_created_59a307_idx",
            old_name="sales_deliv_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverysession",
            new_name="sales_deliv_deliver_fbb9ad_idx",
            old_name="sales_deliv_status_type_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverysession",
            new_name="sales_deliv_deliver_ee6798_idx",
            old_name="sales_deliv_type_date_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverysession",
            new_name="sales_deliv_assigne_512a18_idx",
            old_name="sales_deliv_assigned_date_idx",
        ),
    ]
