# Generated by Django 5.0.14 on 2025-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo (optional)",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
            ),
        ),
    ]
