# Generated by Django 5.0.14 on 2025-12-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_remove_user_roles_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department name', max_length=100, null=True),
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['title'], 'verbose_name': 'Job Title', 'verbose_name_plural': 'Job Titles'},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
