# Generated by Django 5.0.14 on 2025-12-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_jobtitle_options_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('SUPERADMIN', 'Super Admin'), ('PICKER', 'Picker'), ('PACKER', 'Packer'), ('DRIVER', 'Driver'), ('BILLING', 'Billing')], default='USER', help_text='Assigned role of the user', max_length=20),
        ),
    ]
