# Generated by Django 5.0.14 on 2025-12-26 10:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courier_code', models.CharField(max_length=50, unique=True)),
                ('courier_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('EXTERNAL', 'External'), ('INTERNAL', 'Internal')], default='EXTERNAL', max_length=10)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('service_area', models.CharField(blank=True, max_length=200, null=True)),
                ('rate_type', models.CharField(choices=[('FLAT', 'Flat Rate'), ('WEIGHT', 'Per Weight'), ('DISTANCE', 'Per Distance')], default='FLAT', max_length=10)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cod_supported', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'db_table': 'couriers',
                'ordering': ['-created_at'],
            },
        ),
    ]
