# Generated by hand to add DELIVERY role to choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('SUPERADMIN', 'Super Admin'), ('PICKER', 'Picker'), ('PACKER', 'Packer'), ('DRIVER', 'Driver'), ('DELIVERY', 'Delivery'), ('BILLING', 'Billing')], default='USER', help_text='Assigned role of the user', max_length=20),
        ),
    ]
