# Generated by Django 5.0.14 on 2026-03-10 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_delivery_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tray",
            fields=[
                (
                    "tray_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tray_code", models.CharField(max_length=50, unique=True)),
                ("tray_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tray",
                "verbose_name_plural": "Trays",
                "db_table": "trays",
                "ordering": ["-created_at"],
            },
        ),
    ]
