# Generated by Django 5.0.14 on 2026-03-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_tray"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tray",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tray",
            name="status",
        ),
        migrations.RemoveField(
            model_name="tray",
            name="tray_name",
        ),
    ]
