# Generated by Django 5.0.14 on 2026-03-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_tray_description_remove_tray_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tray",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
