# Generated by Django 5.2.13 on 2026-04-28 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_code", models.CharField(db_index=True, max_length=30)),
                ("client_name", models.CharField(max_length=250)),
                ("agent", models.CharField(blank=True, max_length=30, null=True)),
                ("area", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PROMISED", "Payment Promised"),
                            ("PARTIAL", "Partial Payment"),
                            ("NO_RESPONSE", "No Response"),
                            ("DISPUTE", "Dispute Raised"),
                            ("PAID", "Payment Received"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("next_followup_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followups_logged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "followup_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_code", models.CharField(db_index=True, max_length=30)),
                ("client_name", models.CharField(max_length=250)),
                ("agent", models.CharField(blank=True, max_length=30, null=True)),
                ("area", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("oldest_due_days", models.IntegerField(default=0)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("OVERDUE", "Overdue"),
                            ("DUE_SOON", "Due This Week"),
                            ("HIGH_RISK", "High Risk"),
                            ("NO_FOLLOWUP", "No Follow-Up Logged"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "followup_alert",
                "ordering": ["-oldest_due_days", "-outstanding_amount"],
            },
        ),
    ]
