# Generated by Django 5.2.13 on 2026-04-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_followup", "0003_widen_area_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="channel",
            field=models.CharField(
                choices=[
                    ("PHONE", "Phone Call"),
                    ("WHATSAPP", "WhatsApp"),
                    ("EMAIL", "Email"),
                    ("VISIT", "Field Visit"),
                ],
                default="PHONE",
                max_length=20,
            ),
        ),
    ]
