# Generated by Django 5.0.14 on 2026-04-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_followup", "0004_followup_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="promised_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
