# Generated by Django 5.0.14 on 2026-04-29 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_followup", "0005_followup_promised_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentalert",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("OVERDUE", "Overdue"),
                    ("DUE_SOON", "Due This Week"),
                    ("HIGH_RISK", "High Risk"),
                    ("NO_FOLLOWUP", "No Follow-Up Logged"),
                    ("ESCALATED", "Escalated To You"),
                ],
                max_length=20,
            ),
        ),
    ]
