# Generated by Django 5.0.14 on 2026-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeveloperSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_manual_picking_completion",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, picked invoices remain visible in Picking Management with a Complete button",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Developer Settings",
                "verbose_name_plural": "Developer Settings",
            },
        ),
    ]
