# Generated by Django 5.0.14 on 2026-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developersettings",
            name="enable_bulk_picking",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, allows bulk picking of multiple invoices at once",
            ),
        ),
    ]
